apiVersion: v1
kind: Pod
metadata:
  name: gopher-pod
spec:
  containers:
    - name: gopher-container
      image: busybox
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
      resources:
        requests:
          hongxuming.com/gopher: "1"
        limits:
          hongxuming.com/gopher: "1"